dist: focal
language: python
python:
  - "3.10"

install:
  - pip install -r requirements.txt

script:
  - black --check . 
  - pytest

deploy:
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  region: "us-west-2"
  app: "mysitev2"
  env: "mysitev2-env"
  bucket_name: "elasticbeanstalk-us-west-2-481665104411"
  on:
    branch: master